# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 390090df814abc731f5286df8b684eeb0b901f361621a24842b01226c8bd3ae1ee294f263c30a8d01b9e609ba6bb37bb0e9dc71c73cc5fe62e52f290f66e171b

test:
  secret_key_base: f8784414aa27cb175b7a2bc1bde9a7fc98569e797068fe678b24493b7aa90f10d7a583c3931b1280717347821d6fbe9b3558ebf0446a927874049fe20de6f8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
